[scheduler] Enhancement: Update group functions
microsoft/demikernel pull request #1181
Opened 2024-03-12 13:55 UTC by carvalhof

This PR updates `next_runnable_group` and `get_offsets_for_ready_tasks` functions to avoid some memory allocations.

2024-03-13 17:58 UTC, ppenna requested changes
Blocking merge to be able to run benchmarks.

2024-03-13 20:22 UTC, iyzhang requested changes

2024-03-13 20:22 UTC, iyzhang commented on src/rust/runtime/scheduler/scheduler.rs
> +
Thanks for catching this!

2024-03-13 20:22 UTC, iyzhang commented on src/rust/runtime/scheduler/group.rs
> +                offsets.push(offset);
I believe this changes the behavior into a lifo queue of the ready to run tasks. Is there a way that we can do this and still keep it fifo?

2024-03-19 23:47 UTC, iyzhang commented
Microbenchmarks (these microbenchmarks from PR #1198 run 1024 coroutines that are all runnable)
| | run_any | run_any_background |
|dev |1627 ns +/- 8 | 1451 ns +/- 5|
|this PR|1665 ns +/- 19 | 1574 ns +/-17|

2024-04-06 00:18 UTC, closed without merging