[libos] Enhancement: Update imports in NetworkLibOS
microsoft/demikernel pull request #1184
Opened 2024-03-12 18:22 UTC by carvalhof

This PR updates `SharedNetworkLibOS` import in `NetworkLibOS`.

2024-03-13 17:58 UTC, ppenna requested changes
Blocking merge to be able to run benchmarks.

2024-03-13 20:24 UTC, iyzhang approved these changes
LGTM. I'm a little confused why this even compiled for the other libOSes.

2024-03-14 01:12 UTC, carvalhof commented
> LGTM. I'm a little confused why this even compiled for the other libOSes.

Actually, if you make `LIBOS=catnip`, for instance, it's OK. However, if you change `Cargo.toml`:

from

```
[features]
default = ["catnap-libos"]
```

to

```
[features]
default = ["catnip-libos"]
```

and `make LIBOS=catnip`

you got this error:

> error[E0412]: cannot find type `SharedNetworkLibOS` in this scope
>   --> src/rust/demikernel/libos/network/mod.rs:57:12
>    |
> 57 |     Catnip(SharedNetworkLibOS<SharedInetStack<SharedDPDKRuntime>>),
>    |            ^^^^^^^^^^^^^^^^^^ not found in this scope

   
   
This error occurs even using `catnip`, `catpowder`, and `catloop` on `Cargo.toml`.

2024-03-20 18:53 UTC, ppenna approved these changes

2024-03-20 18:54 UTC, merged